apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: windows-debug-17263
  name: windows-debug-17263
  namespace: win
spec:
  containers:
  - image: ghcr.io/jsturtevant/windows-debug:v1.0.0
    imagePullPolicy: Always
    name: windows-debug-17263
    resources: {}
    volumeMounts:
    - mountPath: /tmp
      name: test-volume
    command:
      - powershell 
      - Invoke-Webrequest https://www.microolap.com/downloads/tcpdump/tcpdump_trial_license.zip -useBasicParsing -OutFile C:\tmp\tcpdump.zip;
      - Invoke-WebRequest -UseBasicParsing https://aka.ms/downloadazcopy-v10-windows -OutFile c:\tmp\azcopy.zip;
      - Expand-Archive C:\tmp\tcpdump.zip -DestinationPath C:\tmp\; 
      - Expand-Archive c:\tmp\azcopy.zip -DestinationPath C:\tmp\;
      - c:\tmp\tcpdump -G 10 -W 1 -w c:\tmp/tcpdump.logs;
      - cd C:\tmp\azcopy*;
      - ./azcopy.exe copy "C:\tmp\tcpdump.logs" "https://storageovidiuborlean.blob.core.windows.net/logs?sp=racwdli&st=2022-10-13T13:37:39Z&se=2025-10-13T21:37:39Z&spr=https&sv=2021-06-08&sr=c&sig=pRLKZgGVo77BVZa0Suki0CZo5fMReXi8VrXt1wnAH8A%3D"
  volumes:
  - name: test-volume
    hostPath:
      path: /tmp
      type: Directory
  dnsPolicy: ClusterFirst
  hostNetwork: true
  nodeSelector:
    kubernetes.io/os: windows
  restartPolicy: Never
  securityContext:
    windowsOptions:
      hostProcess: true
      runAsUserName: NT AUTHORITY\SYSTEM
status: {}